openapi: 3.0.3

info:
  title: Mini Doodle API
  version: 1.0.0

servers:
  - url: http://localhost:8080/mini-doodle/api/v1

paths:
  /user/register:
    $ref: ./paths/register-user.yaml#/registerUser

  /availability/create:
    $ref: ./paths/add-availability.yaml#/add-availability

  /availability/remove:
    $ref: ./paths/remove-availability.yaml#/remove-availability

  /meetings/schedule:
    $ref: ./paths/schedule-meeting.yaml#/scheduleMeeting

  /meetings/cancel/{id}:
    $ref: ./paths/cancel-meeting.yaml#/cancelMeeting